### Baseline Model
Based on popularity only

In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
song_df_1 = pd.read_csv('./data/kaggle_visible_evaluation_triplets.txt', sep='\t', header=None)
song_df_1.columns = ['user_id', 'song_id', 'listen_count']
song_df_1.head()

                                    user_id             song_id  listen_count
0  fd50c4007b68a3737fe052d5a4f78ce8aa117f3d  SOBONKR12A58A7A7E0             1
1  fd50c4007b68a3737fe052d5a4f78ce8aa117f3d  SOEGIYH12A6D4FC0E3             1
2  fd50c4007b68a3737fe052d5a4f78ce8aa117f3d  SOFLJQZ12A6D4FADA6             1
3  fd50c4007b68a3737fe052d5a4f78ce8aa117f3d  SOHTKMO12AB01843B0             1
4  fd50c4007b68a3737fe052d5a4f78ce8aa117f3d  SODQZCY12A6D4F9D11             1

In [3]:
song_df_2 = pd.read_table('./data/unique_tracks.txt', sep='<SEP>', header=None)
song_df_2.columns = ['track_id', 'song_id', 'artist_name', 'title']
song_df_2.head()

             track_id             song_id       artist_name              title
0  TRMMMYQ128F932D901  SOQMMHC12AB0180CB8  Faster Pussy cat       Silent Night
1  TRMMMKD128F425225D  SOVFVAK12A8C1350D9  Karkkiautomaatti        Tanssi vaan
2  TRMMMRX128F93187D9  SOGTUKN12AB017F4F1    Hudson Mohawke  No One Could Ever
3  TRMMMCH128F425532C  SOBNYVR12A8C13558C       Yerba Brava      Si Vos Querés
4  TRMMMWA128F426B589  SOHSBXH12A8C13B0DF        Der Mystic   Tangle Of Aspens

In [4]:
song_df = pd.merge(song_df_1, song_df_2.drop_duplicates(['song_id']), on="song_id", how="left")
song_df.head()

,user_id,song_id,listen_count,track_id,artist_name,title
0,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOBONKR12A58A7A7E0,1,TRAEHHJ12903CF492F,Dwight Yoakam,You're The One
1,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOEGIYH12A6D4FC0E3,1,TRLGMFJ128F4217DBE,Barry Tuckwell/Academy of St Martin-in-the-Fie...,Horn Concerto No. 4 in E flat K495: II. Romanc...
2,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOFLJQZ12A6D4FADA6,1,TRTNDNE128F1486812,Cartola,Tive Sim
3,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOHTKMO12AB01843B0,1,TRASTUE128F930D488,Lonnie Gordon,Catch You Baby (Steve Pitron & Max Sanna Radio...
4,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SODQZCY12A6D4F9D11,1,TRFPLWO128F1486B9E,Miguel Calo,El Cuatrero

### Data Preparation

#### Data Transformation

In [38]:
song_df['song_artist'] = song_df['title'] + ' - ' + song_df['artist_name']
song_df.head()

,user_id,song_id,listen_count,track_id,artist_name,title,song_artist
0,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOBONKR12A58A7A7E0,1,TRAEHHJ12903CF492F,Dwight Yoakam,You're The One,You're The One - Dwight Yoakam
1,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOEGIYH12A6D4FC0E3,1,TRLGMFJ128F4217DBE,Barry Tuckwell/Academy of St Martin-in-the-Fie...,Horn Concerto No. 4 in E flat K495: II. Romanc...,Horn Concerto No. 4 in E flat K495: II. Romanc...
2,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOFLJQZ12A6D4FADA6,1,TRTNDNE128F1486812,Cartola,Tive Sim,Tive Sim - Cartola
3,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SOHTKMO12AB01843B0,1,TRASTUE128F930D488,Lonnie Gordon,Catch You Baby (Steve Pitron & Max Sanna Radio...,Catch You Baby (Steve Pitron & Max Sanna Radio...
4,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,SODQZCY12A6D4F9D11,1,TRFPLWO128F1486B9E,Miguel Calo,El Cuatrero,El Cuatrero - Miguel Calo

In [39]:
len(song_df)

1450933

In [40]:
song_grouped = song_df.groupby(['song_artist']).agg({'listen_count': 'count'}).reset_index()
song_grouped.sort_values(by=['listen_count'],ascending=False)

                                              song_artist  listen_count
116489                           Sehr kosmisch - Harmonia          5043
147830                                       Undo - Björk          4483
160385                     You're The One - Dwight Yoakam          4136
33504   Dog Days Are Over (Radio Edit) - Florence + Th...          3780
110726                            Revelry - Kings Of Leon          3672
...                                                   ...           ...
77923                         Life Indoors - 1 Mile North             1
77921               Life In The Tropics - The Rippingtons             1
77920                  Life In The Real World - Firehouse             1
77917              Life In The Gladhouse - Modern English             1
162042     þetta Gerist á Bestu Bæjum - Johann Johannsson             1

[162043 rows x 2 columns]

In [41]:
grouped_sum = song_grouped['listen_count'].sum()
song_grouped['percentage']  = song_grouped['listen_count'].div(grouped_sum)*100
#song_grouped.sort_values(['play_count'], ascending=False )

song_grouped.sort_values(['listen_count', 'song_artist'], ascending = [0,1]).head(20)

,song_artist,listen_count,percentage
116489,Sehr kosmisch - Harmonia,5043,0.347570
147830,Undo - Björk,4483,0.308974
160385,You're The One - Dwight Yoakam,4136,0.285058
33504,Dog Days Are Over (Radio Edit) - Florence + Th...,3780,0.260522
110726,Revelry - Kings Of Leon,3672,0.253079
116238,Secrets - OneRepublic,3430,0.236400
57994,Horn Concerto No. 4 in E flat K495: II. Romanc...,3272,0.225510
56238,Hey_ Soul Sister - Train,2791,0.192359
44083,Fireflies - Charttraxx Karaoke,2725,0.187810
143090,Tive Sim - Cartola,2668,0.183882
96987,OMG - Usher featuring will.i.am,2260,0.155762
35966,Drop The World - Lil Wayne / Eminem,2226,0.153419
21719,Catch You Baby (Steve Pitron & Max Sanna Radio...,2097,0.144528
84700,Marry Me - Train,1990,0.137153
148561,Use Somebody - Kings Of Leon,1911,0.131708
120204,Sincerité Et Jalousie - Alliance Ethnik,1797,0.123851
110335,Représente - Alliance Ethnik,1769,0.121922
20670,Canada - Five Iron Frenzy,1727,0.119027
4166,Ain't Misbehavin - Sam Cooke,1712,0.117993
107099,Pursuit Of Happiness (nightmare) - Kid Cudi / ...,1683,0.115994

In [42]:
users = song_df['user_id'].unique()
len(users) ## return 365 unique users ???

110000

In [43]:
songs = song_df['song_artist'].unique()
len(songs) ## return 5151 unique songs ???

162044

### Model

In [44]:
# split train and test data
train_data, test_data = train_test_split(song_df, test_size = 0.3, random_state=0)

In [45]:
train_data.head()

,user_id,song_id,listen_count,track_id,artist_name,title,song_artist
308422,4cd3adf60460e695f71f732965a27f43475ebbe3,SOVTYEV12A8C1427B6,1,TRGEHKZ128F42B749A,Dave Grusin / Mike Fisher / Abraham Laboriel /...,Fiesta,Fiesta - Dave Grusin / Mike Fisher / Abraham L...
973722,7808c8490c0bd2ddca18a316c04666391021b365,SOYVAFI12AB0180032,1,TRUVPCW128F4292377,Faithless,Take The Long Way Home,Take The Long Way Home - Faithless
264191,31232a3bcbcbc4ef0dfd662843585d6d9fcce868,SOJSAWE12A58A7F76E,1,TRIAVQO128F4236D1E,Sugar Ray feat. Super Cat,Fly (Remastered LP Version),Fly (Remastered LP Version) - Sugar Ray feat. ...
637045,7c1ff69f5fe793b3291de481001bb2baa08f3bcc,SOGOVIF12A58A78DCE,1,TRCHBEJ128F4248D55,Opeth,Porcelain Heart (Album Version),Porcelain Heart (Album Version) - Opeth
1177626,3b94c3b70b2e440a00fae9c63bd3d63b4b094bcb,SOBOAFP12A8C131F36,1,TRCPAGR128F423A01A,Jason Mraz & Colbie Caillat,Lucky (Album Version),Lucky (Album Version) - Jason Mraz & Colbie Ca...

In [46]:
#Class for Popularity based Recommender System modelclass popularity_recommender_py():    
def __init__(self):        
    self.train_data = None        
    self.user_id = None        
    self.item_id = None        
    self.popularity_recommendations = None            

#Create the popularity based recommender system model    
def create(self, train_data, user_id, item_id): 
    self.train_data = train_data
    self.user_id = user_id        
    self.item_id = item_id         

    #Get a count of user_ids for each unique song as   recommendation score
    train_data_grouped = train_data.groupby([self.item_id]).agg({self.user_id: 'count'}).reset_index()        
    train_data_grouped.rename(columns = {'user_id': 'score'},inplace=True)            
    #Sort the songs based upon recommendation score
    train_data_sort = train_data_grouped.sort_values(['score', self.item_id], ascending = [0,1])            
    #Generate a recommendation rank based upon score
    train_data_sort['Rank'] = train_data_sort['score'].rank(ascending=0, method='first')
    #Get the top 10 recommendations
    self.popularity_recommendations = train_data_sort.head(10)     
    
    
#Use the popularity based recommender system model to    
#make recommendations    
    
def recommend(self, user_id):            
    user_recommendations = self.popularity_recommendations                 
    #Add user_id column for which the recommendations are being generated        
    user_recommendations['user_id'] = user_id            
    #Bring user_id column to the front        
    cols = user_recommendations.columns.tolist()        
    cols = cols[-1:] + cols[:-1]        
    user_recommendations = user_recommendations[cols]
    return user_recommendations

##https://towardsdatascience.com/how-to-build-a-simple-song-recommender-296fcbc8c85

In [47]:
import numpy as np
import pandas

#Class for Popularity based Recommender System model
class popularity_recommender_py():
    def __init__(self):
        self.train_data = None
        self.user_id = None
        self.item_id = None
        self.popularity_recommendations = None
        
    #Create the popularity based recommender system model
    def create(self, train_data, user_id, item_id):
        self.train_data = train_data
        self.user_id = user_id
        self.item_id = item_id

        #Get a count of user_ids for each unique song as recommendation score
        train_data_grouped = train_data.groupby([self.item_id]).agg({self.user_id: 'count'}).reset_index()
        train_data_grouped.rename(columns = {'user_id': 'score'},inplace=True)
    
        #Sort the songs based upon recommendation score
        train_data_sort = train_data_grouped.sort_values(['score', self.item_id], ascending = [0,1])
    
        #Generate a recommendation rank based upon score
        train_data_sort['Rank'] = train_data_sort['score'].rank(ascending=0, method='first')
        
        #Get the top 10 recommendations
        self.popularity_recommendations = train_data_sort.head(10)

    #Use the popularity based recommender system model to
    #make recommendations
    def recommend(self, user_id):    
        user_recommendations = self.popularity_recommendations
        
        #Add user_id column for which the recommendations are being generated
        user_recommendations['user_id'] = user_id
    
        #Bring user_id column to the front
        cols = user_recommendations.columns.tolist()
        cols = cols[-1:] + cols[:-1]
        user_recommendations = user_recommendations[cols]
        
        return user_recommendations

In [48]:
# popularity based model
#import Recommenders as Recommenders

pm = popularity_recommender_py()
pm.create(train_data, 'user_id', 'song_artist')
#user the popularity model to make some prediction
user_id = users[5]
pm.recommend(user_id)

,user_id,song_artist,score,Rank
100543,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Sehr kosmisch - Harmonia,3513,1.0
127831,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Undo - Björk,3168,2.0
138725,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,You're The One - Dwight Yoakam,2894,3.0
28847,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Dog Days Are Over (Radio Edit) - Florence + Th...,2640,4.0
95557,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Revelry - Kings Of Leon,2580,5.0
100324,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Secrets - OneRepublic,2397,6.0
50011,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Horn Concerto No. 4 in E flat K495: II. Romanc...,2264,7.0
48476,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Hey_ Soul Sister - Train,1956,8.0
37981,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Fireflies - Charttraxx Karaoke,1912,9.0
123715,91b8fac7dc5e03f6cfaf6e2aa7171f14a8354d62,Tive Sim - Cartola,1877,10.0

In [49]:
user_id = 'fd50c4007b68a3737fe052d5a4f78ce8aa117f3d'

In [50]:
pm.recommend(user_id)

,user_id,song_artist,score,Rank
100543,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Sehr kosmisch - Harmonia,3513,1.0
127831,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Undo - Björk,3168,2.0
138725,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,You're The One - Dwight Yoakam,2894,3.0
28847,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Dog Days Are Over (Radio Edit) - Florence + Th...,2640,4.0
95557,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Revelry - Kings Of Leon,2580,5.0
100324,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Secrets - OneRepublic,2397,6.0
50011,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Horn Concerto No. 4 in E flat K495: II. Romanc...,2264,7.0
48476,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Hey_ Soul Sister - Train,1956,8.0
37981,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Fireflies - Charttraxx Karaoke,1912,9.0
123715,fd50c4007b68a3737fe052d5a4f78ce8aa117f3d,Tive Sim - Cartola,1877,10.0